// Generated by `tools/toolsmith`. Runs this package's tool body against every
// case in `cases.json`, twice each, with all ambient nondeterminism shadowed.
//
// Re-running `scaffold` regenerates this file; it never touches the body or
// `cases.json`. Add cases by editing `cases.json`, never by editing this file.

import { dirname } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

// Dynamic, because a published satellite tree ships the plugin without the repo's
// tools/ directory — there the harness is genuinely absent and a skip is the honest
// result. A REPORTED skip, never a silent pass: a suite that quietly tests nothing
// is the failure mode this whole pipeline exists to prevent.
let defineToolTests;
try {
	({ defineToolTests } = await import("../../tools/toolsmith/harness.mjs"));
} catch {
	test("toolsmith harness is absent — cases did NOT run (satellite checkout?)", {
		skip: "harness not resolvable from this tree",
	}, () => {
		// intentionally empty: the skip reason is the report
	});
}

if (defineToolTests) {
	defineToolTests(here);
}
